spring:
  profiles:
    active: dev
  redis:
    host: 192.168.30.95
    password: wO2f@j0q16loYa5d
    port: 6379
    database: 0
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms
        timeout: 10000ms